# -*- coding: utf-8 -*-
"""15/02/2024 - 16/02/2024 - FOR .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wM_xFk4PVxhKCFq1d2jO1yAcvhnC5OG8
"""

Programa Primeiro_Looping

var
         X,R,cont: inteiro

Inicio
         para cont de 1 até 4 passo 1 faça
         leia (x)
         R <- X*12
         escreva(R)
       fim_para
fim

8maior_numero = float('-inf')

for banana in range(5):
  numero = float(input(f"digite o {banana+1}º numero: "))
  if numero > maior_numero:
    maior_numero = numero

  print(f"O maior numero digitado é: {maior_numero}")

for numero in range(1000, 1100):
    if numero % 11 == 2:
        print(numero)

numero = int()
soma = int()
media = int()

for contador in range(5):
  numero = int(input(f"Digite o {contador+1}o valor: "))
  soma += numero
  media = soma /5

  print(f"A soma total é {soma} e a média {media}")

numero = int(input("Digite um número para ver a tabuada: "))

print(f"Tabuada do {numero}:")
for contador in range(1, 11):
    resultado = numero * contador
    print(f"{numero} x {contador} = {resultado}")

numero = int(input("Digite um número de 1 a 10: "))

if numero <= 0 or numero >10:
  print("Valor Inválido, insira um valor de 1 a 10.")
else:
  for contador in range(11):
    resultado = numero * contador
    print(f"{numero} x {contador} = {resultado}")

for i in range(1,21):
 print(i)

print(list(range(1,21)))

for i in range(1,51):
    if i % 2 != 0:
      print(i)

n1 = int(input("Digite o primeiro Número: "))
n2 = int(input("Digite o segundo Número: "))

for contador in range( n1 + 1 , n2):
  print(contador)

for contador in range( n2 + 1 , n1):
  print(contador)

faturamento_lojab = 54000
faturamento_lojaa = float()

for contador in range (1,6):
  faturamento_lojaa += float(input("Digite o valor do faturamento: "))

if faturamento_lojaa > faturamento_lojab:
  print("A loja A superou a loja B em ",faturamento_lojaa - faturamento_lojab)

else:
  print("A loja A não superou a Loja B")

"""Faça um programa que peça 10 números inteiros, calcule e mostre a
quantidade de números pares e a quantidade de números impares.
"""

pares = 0
impares = 0

for i in range (1,11):
  numero =int(input(f"Digite o {i} numero inteiro."))

  if numero % 2 == 0:
    pares += 1
  else:
    impares += 1

print(f"A quantidade de numeros pares é: {pares}, e a quantidade de numeros impares é: {impares}.")

""" Um funcionário de uma empresa recebe aumento salarial anualmente:
Sabe-se que:
Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00;
Em 1996 recebeu aumento de 1,5% sobre seu salário inicial;
A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao
dobro do percentual do ano anterior. Faça um programa que determine o
salário atual desse funcionário. Após concluir isto, altere o programa
permitindo que o usuário digite o salário inicial do funcionário.
"""

salario = float(input("Digite o salário inicial do funcionário: "))
aumento = 1.5

for i in range (1996,2025):
  atual = salario + (salario *(aumento/100))
  aumento = aumento * 2
  print(f"Salário em {i} = {atual} ")

"""Faça um programa que peça uma nota, entre zero e dez. Mostre uma
mensagem caso o valor seja inválido e continue pedindo até que o usuário
informe um valor válido.
"""

for nota in range(999):
  nota = float(input("Digite uma nota de 0 a 10: "))
  if nota >= 0 and nota <= 10:
    print("Nota válida")
    break
  else:
    print("Nota inválida")